### ISSUE TITLE
Initialization type or name space not found in V 0.0.3

### ISSUE THREAD

**Issue by ahmedelsyaed** [ChasakisD/Xamarin.Forms-Coordinator-Workaround#3]
In the .adnroid project the initialization not found using v 0.0.3, after downgrade to version to 0.0.1 the 
CoordinatorWorkaround.Droid is working fine.

**Comment by ChasakisD** [comment]
There are no changes to the initialization process. Could you post an example project or some additional information?

**Comment by ahmedelsyaed** [comment]
on another version of VS it seems that there is no issue.
